export const PRESETS = [
  ["nuteral", "Nuteral"],
  ["nuteral-accent", "Nuteral (Accent)"],
  ["codecanon", "CodeCanon"],
  ["anew", "Anew"],
  ["red", "Red"],
  ["rose", "Rose"],
  ["orange", "Orange"],
  ["green", "Green"],
  ["blue", "Blue"],
  ["yellow", "Yellow"],
  ["violet", "Violet"],
  ["modern-minimal", "Modern Minimal"],
  ["violet-bloom", "Violet Bloom"],
  ["t3-chat", "T3 Chat"],
  ["twitter", "Twitter"],
  ["mocha-mousse", "Mocha Mousse"],
  ["bubblegum", "Bubblegum"],
  ["amethyst-haze", "Amethyst Haze"],
  ["notebook", "Notebook"],
  ["doom-64", "Doom 64"],
  ["catppuccin", "Catppuccin"],
  ["graphite", "Graphite"],
  ["perpetuity", "Perpetuity"],
  ["kodama-grove", "Kodama Grove"],
  ["cosmic-night", "Cosmic Night"],
  ["tangerine", "Tangerine"],
  ["quantum-rose", "Quantum Rose"],
  ["nature", "Nature"],
  ["bold-tech", "Bold Tech"],
  ["elegant-luxury", "Elegant Luxury"],
  ["amber-minimal", "Amber Minimal"],
  ["supabase", "Supabase"],
  ["neo-brutalism", "Neo Brutalism"],
  ["solar-dusk", "Solar Dusk"],
  ["claymorphism", "Claymorphism"],
  ["cyberpunk", "Cyberpunk"],
  ["pastel-dreams", "Pastel Dreams"],
  ["clean-slate", "Clean Slate"],
  ["caffeine", "Caffeine"],
  ["ocean-breeze", "Ocean Breeze"],
  ["retro-arcade", "Retro Arcade"],
  ["midnight-bloom", "Midnight Bloom"],
  ["candyland", "Candyland"],
  ["northern-lights", "Northern Lights"],
  ["vintage-paper", "Vintage Paper"],
  ["sunset-horizon", "Sunset Horizon"],
  ["starry-night", "Starry Night"],
  ["claude", "Claude"],
  ["vercel", "Vercel"],
  ["darkmatter", "Darkmatter"],
  ["mono", "Mono"],
  ["soft-pop", "Soft Pop"],
  ["sage-garden", "Sage Garden"],
] as const satisfies [string, string][]

/**
 * ---------------------------------------------------------
 * Type Definitions
 * ---------------------------------------------------------
 */
export type PresetKeys = (typeof PRESETS)[number][0]

/** A tuple of [id, label] describing a single preset — built-in or custom. */
export type PresetTuple = readonly [string, string]
